### ISSUE TITLE
Dockerfile for Ubuntu 12.04 build

### ISSUE THREAD

**Issue by sjames1958gm** [telegramdesktop/docker_linux_build#1]
Here is a file that builds telegram in a docker 12.04 container as a starting point.
[dockerfile.txt](https://github.com/telegramdesktop/docker/files/1380111/dockerfile.txt)

**Comment by auchri** [comment]
Let's stick to the issue in the main repo until we have a working dockerfile which works with the new instructions (which should get published soon): https://github.com/telegramdesktop/tdesktop/issues/3978
