### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by mirhmousavi** [telegramdesktop/docker_linux_build#3]
after running ./build_tdesktop.sh i got these error

ry
 #include "opus.h"
          ^~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/libtgvoip.dir/TBuild/tdesktop/Telegram/ThirdParty/libtgvoip/CongestionControl.o] Error 1
make[1]: *** [CMakeFiles/libtgvoip.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  5%] Building CXX object CMakeFiles/crl.dir/TBuild/tdesktop/Telegram/ThirdParty/crl/src/crl/qt/crl_qt_semaphore.o
[  5%] Building CXX object CMakeFiles/crl.dir/TBuild/tdesktop/Telegram/ThirdParty/crl/src/crl/winapi/crl_winapi_async.o
[  5%] Building CXX object CMakeFiles/crl.dir/TBuild/tdesktop/Telegram/ThirdParty/crl/src/crl/winapi/crl_winapi_list.o
[  5%] Building CXX object CMakeFiles/crl.dir/TBuild/tdesktop/Telegram/ThirdParty/crl/src/crl/winapi/crl_winapi_semaphore.o
Linking CXX static library obj.target/libcrl.a
[  5%] Built target crl
Linking CXX executable tests_flat_map
Linking CXX executable tests_flat_set
[  5%] Built target tests_flat_map
[  5%] Built target tests_flat_set
make: *** [all] Error 2

**Comment by auchri** [comment]
This build scripts aren't finished yet because I've got no time yet to adjust the script to the new build instructions.
I hope to fix them soon.

**Comment by mirhmousavi** [comment]
I didn't get it
I should run the script to complie and launch Telegram, right? and you say it is not complete yet?
or i am wrong

**Comment by auchri** [comment]
The docker container is only supposed to build TDesktop without installing all the dependencies on your computer. The container will only build TDesktop.

And yes, the scripts aren't finished yet.

**Comment by mirhmousavi** [comment]
so it is not practical?

**Comment by auchri** [comment]
_Not yet._
But you are welcome to create a PR which adjusts the [Dockerfile](https://github.com/telegramdesktop/docker_linux_build/blob/auchri-patch-1/Dockerfile) to the new [build instructions](https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md).
